package com.example.e_librarium.navigation

const val ROUTE_ADD_BOOKS = "addBooks"
const val ROUTE_BOOKS_HOME = "booksHome"
const val ROUTE_EDIT_BOOKS = "editBooks"
const val ROUTE_VIEW_BOOKS = "viewBooks"
const val ROUTE_VIEW_ALL_BOOKS = "viewAllBooks"
const val ROUTE_VIEW_BOOKS_GUEST = "viewBooksGuest"
const val ROUTE_VIEW_ALL_BOOKS_CLIENT = "viewAllBooksClient"
const val ROUTE_BORROW_BOOKS = "borrowBooks"
const val ROUTE_BORROW_HOME = "borrowHome"
const val ROUTE_VIEW_CLIENTS = "viewClients"
const val ROUTE_CLIENT_LOGIN = "clientLogIn"
const val ROUTE_CLIENT_REGISTER = "clientRegister"
const val ROUTE_CLIENT_HOME = "clientsHome"
const val ROUTE_VIEW_CLIENT_INFO = "viewClientInfo"
const val ROUTE_EDIT_CLIENT_INFO = "editClientInfo"
const val ROUTE_VIEW_BORROWED_BOOKS = "viewBorrowedBooks"
const val ROUTE_HOME = "home"
const val ROUTE_RETURN_BOOKS = "returnBooks"
const val ROUTE_RETURN_HOME = "returningHome"
const val ROUTE_STAFF_LOGIN = "staffLogIn"
const val ROUTE_STAFF_REGISTER = "staffRegister"
const val ROUTE_STAFF_HOME = "staffHome"
const val ROUTE_VIEW_STAFF_INFO = "viewStaffInfo"
const val ROUTE_EDIT_STAFF_INFO = "editStaffInfo"
const val ROUTE_STAFF_FEEDBACK  = "feedbackScreenStaff"
const val ROUTE_CLIENT_FEEDBACK  = "feedbackScreenClient"
